### ISSUE TITLE
CurrentUser is null when calling contentService.Copy(content, targetId, false);

### ISSUE THREAD

**Issue by bachhuong** [rhythmagency/whodunit#1]
Hi Rhythm,

Thank you for having developed this package, this is very valuable. 

When I executed this command: 
`contentService.Copy(content, targetId, false);`

I have met the exception below:
> [NullReferenceException: Object reference not set to an instance of an object.]
>   Whodunit.app.Events.ContentLogging.GetUserSignature(User source) in C:\r\whodunit\src\Whodunit.app\Events\ContentLogging.cs:175
>   Whodunit.app.Events.ContentLogging.ContentService_Copied(IContentService sender, CopyEventArgs`1 e) in C:\r\whodunit\src\Whodunit.app\Events\ContentLogging.cs:100

Could you please review if there is something wrong ? 

Thank you.

Regards,
Bach Huong

**Comment by Nicholas-Westby** [comment]
Thanks for the report, Bach. I am able to reproduce. Will look into a fix.

**Comment by Nicholas-Westby** [comment]
This is fixed in 0.2.4, which you can download here: https://our.umbraco.org/projects/backoffice-extensions/whodunit/

Thanks again for the report.
